# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  pull_request: 
    branches:
      - main
      - develop
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string


jobs:
  greet:
    runs-on: windows-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"

    - name: Check sudo
      run: sudo ls
