# This is a basic workflow that is manually triggered

name: My workflow

on:
  pull_request: 
    branches:
      - main
      - develop
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string


jobs:
  greet:
    runs-on: 	ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"

    - name: Install Docker
      run: sudo apt install docker.io
